apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: flux
spec:
  interval: 1h
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
      interval: 1h
  releaseName: node-feature-discovery
  targetNamespace: node-feature-discovery
  storageNamespace: node-feature-discovery
  values:
    worker:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          effect: "NoSchedule"
      securityContext:
        seccompProfile:
          type: RuntimeDefault
