#!/bin/sh

# Original source: https://github.com/git/git/blob/master/templates/hooks--pre-commit.sample

# Accept optional ref to check against, useful for hook testing
# Example: ./.githooks/pre-commit origin/HEAD
head=${1:-HEAD}

if git rev-parse --verify $head >/dev/null 2>&1; then
	against=$head
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

# Avoid non-ASCII filenames
if [ "$(git diff --cached --name-only --diff-filter=A -z $against | LC_ALL=C tr -d '[ -~]\0' | wc -c | tr -d '[:space:]')" != "0" ]; then
    echo "Error: Attempt to add a non-ASCII file name."
    exit 1
fi

# Check for non-encrypted secrets
unencrypted=$(
    git diff --cached --name-only --diff-filter=AM $against | \
        xargs --no-run-if-empty grep --files-with-matches --perl-regexp --ignore-case '^kind:\s+secret' | \
        xargs --no-run-if-empty grep --files-without-match 'ENC.AES256' | \
        xargs --no-run-if-empty grep --files-without-match '^    gitops/encrypt: false'
)
if [ "$unencrypted" != "" ]; then
    echo "Error: Found unencrypted secrets:"
    echo
    for file in $unencrypted; do
        echo "- $file"
    done
    exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
