apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: cilium-values
    namespace: flux
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
