apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ${name}
  namespace: flux
spec:
  interval: 1h
  releaseName: ${name}
  dependsOn:
    - name: nfs-subdir-external-provisioner
    - name: cert-manager
    - name: ingress-nginx
  targetNamespace: ${namespace}
  storageNamespace: ${namespace}
  chart:
    spec:
      chart: ntfy
      version: 0.1.7
      sourceRef:
        kind: HelmRepository
        name: ${name}
      interval: 1h
  values:
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: ${issuer}
      hosts:
        - host: ${hostname}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: ${name}-tls
          hosts:
            - ${hostname}
    config:
      enabled: true
      data:
        base-url: "https://${hostname}"
        auth-file: "/var/cache/ntfy/user.db"
        auth-default-access: "deny-all"
        cache-file: "/var/cache/ntfy/cache.db"
        attachment-cache-dir: "/var/cache/ntfy/attachments"
        behind-proxy: true
    persistence:
      enabled: true
      size: 1Gi
