apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ${name}
  namespace: flux
spec:
  interval: 1h
  install:
    timeout: 50m
  releaseName: ${name}
  dependsOn:
    - name: nfs-subdir-external-provisioner
    - name: cert-manager
    - name: ingress-nginx
  chart:
    spec:
      chart: ${name}
      version: 2024.2.2
      sourceRef:
        kind: HelmRepository
        name: ${name}
      interval: 1h
  targetNamespace: ${namespace}
  storageNamespace: ${namespace}
  values:
    authentik:
      secret_key: ${secretkey}
      error_reporting:
        enabled: false
      postgresql:
        password: ${dbPassword}
    server:
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: ${issuer}
          kubernetes.io/ingress.class: nginx
        ingressClassName: nginx
        enabled: true
        hosts:
          - ${hostname}
        tls:
          - secretName: ${name}-tls
            hosts:
              - ${hostname}
    postgresql:
      enabled: true
      auth:
        password: ${dbPassword}
    redis:
      enabled: true