apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ${proxmox_ccm_name}
  namespace: flux
spec:
  interval: 1h
  install:
    timeout: 50m
  releaseName: ${proxmox_ccm_name}
  chart:
    spec:
      chart: ${proxmox_ccm_name}
      sourceRef:
        kind: HelmRepository
        name: ${proxmox_ccm_name}
      version: "0.2.0"
  targetNamespace: ${proxmox_ccm_namespace}
  storageNamespace: ${proxmox_ccm_namespace}
  values:
    config:
      clusters:
        - url: ${proxmox_api_url}
          insecure: true
          token_id: "kubernetes@pve!ccm"
          token_secret: ${proxmox_ccm_token}
          region: ${proxmox_ccm_cluster}
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
    logVerbosityLevel: 9
    enabledControllers:
      - cloud-node-lifecycle
