apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: ${proxmox_csi_name}
  namespace: flux
spec:
  interval: 1h
  url: https://github.com/sergelogvinov/proxmox-csi-plugin
  ref:
    branch: main
  ignore: |-
    # exclude all
    /*
    # include charts directory
    !/charts/