apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: kube
  path: ./cluster/apps
  prune: false
  timeout: 5m
