apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: base
  namespace: flux
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: kube
  path: ./base
  prune: false
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: secrets