apiVersion: v1
kind: Secret
metadata:
    name: secrets
    namespace: flux
type: Opaque
stringData:
    adminEmail: ENC[AES256_GCM,data:GoRZKqcjCtG1nARUel0SRyvUQA==,iv:7e3W3MBUazqQ1gvS99u+KxkwEHsa7SOjSJDuGkqzuHg=,tag:Fnfy9hUsGnfq9BRIqNaXaA==,type:str]
    nfsServer: ENC[AES256_GCM,data:RnqCErOAN+B0ITk=,iv:VnpzSt08hlwUUOYcc8UI3nceAVGb0nW9qoM7eoPRJuk=,tag:FaKf851oEmmjQW61on2wuA==,type:str]
    nfsPath: ENC[AES256_GCM,data:Yd7S+4lbxIct,iv:NktHNdkJJi2U8KD2W0ADQUyeoGnAXndbYPG1qqOxWRk=,tag:/2mLz1Kbcoq6To/E4+rwww==,type:str]
    proxmox_ccm_name: ENC[AES256_GCM,data:s0FVAddRcO/zplGPjZIKfsODvcrOu4t5lUlN9MspumE=,iv:rS3FV/uDUhiZSysX8kCxx0m4cY/MLPS+yupGLNLHPWA=,tag:CooqhZJ9O5aYVsYL+30r6w==,type:str]
    proxmox_ccm_namespace: ENC[AES256_GCM,data:tfEygjgFesVgDck=,iv:0P98kn7LsQH9qwBv0RlXuUYAMwFPpkxzXAvDq9Q1n/k=,tag:3neFKTETaTRukTalYwJ6Fw==,type:str]
    proxmox_ccm_token: ENC[AES256_GCM,data:py5tJQ9xkjl4skwQuqDR/7rntm3Rwh8o2h4LNI/f/qd6rzYP,iv:I0ZWw2o7aNV6FlhXQe5NjDfM544onTnN/Aai75EsrcI=,tag:MqdUS0G6bYNQ2CM+B0SI8A==,type:str]
    proxmox_ccm_cluster: ENC[AES256_GCM,data:hikFQVADgkZ79Q==,iv:2zWYDfRjZ/aaVtISdmKRvDsoBoSHv89A2v2QRwR2IBA=,tag:dwVMlAI0BxYQIWQd9zJOxw==,type:str]
    proxmox_api_url: ENC[AES256_GCM,data:ZH/N6oWxwYjP8yEAv31nBCTKeZRiCJ9wDG1Ppfx/EO5GVg==,iv:g3O0K3bGrteUgRhOGTgT7Bmx7pxAzatWyj1HOSeNEkE=,tag:HJoEibQtWPlVRZfq8bl/ww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-08T21:16:11Z"
    mac: ENC[AES256_GCM,data:zFCP+Jf72ZD9StOR3X78skZ/3xdPNSStHCTFBYZShJnDugffruLnLFIdOa2LONZ+wswAIaqGTXsUHxEMM8zHY1PARuB27ST4t3CXM5CNyMPcw6JsqL/Jba8Ly0L+D6xwFkrFAjUizqHe7arpH16ijvHeITS983QAFlxJAOqLt4U=,iv:fA6BjE7l6Sb/3EEwe8Oftyo5GQAVieIcsFRYusLX7B0=,tag:00oS/pSr8QM5+UAz40gVjQ==,type:str]
    pgp:
        - created_at: "2024-03-08T21:16:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2SRLLmgM4SnAQ//b9uY5d3Vwxb4yvsrJWEFNWhoxoRaOttLzeCT8J6O0DKT
            iFgxiVo+asnJdTavXGlzQ5bi//PtukG2E4V9oUpg2MuD4UfOnxxdSclS/OQoUxFq
            J6tLiAo307A29hvT0LBitO1mCBpabppaxjukJTwyqvJwC8YBxgdbBxIT0tmwo+ZZ
            6gU36wep8ghHbfYHblBYk5h55HysmwAmebf4iaZBc5OvA2Os10flADEGJzuWinnM
            9Z3nr8tEQI4zETmTWd7xkLah9UNZ6HngSiEuukZF/OiVa3I6OsQsOdRMl1TiEN+P
            DciWMyqVPgRjGajst0Q6vjkFfM66V3H4uw3bobuh9DiYGPSEOUGvjYnPQYJPSXd0
            Pp1acefwklx8k4vzQiU3WLhgQUVHHYGdkSWyGlkteXJot7CACXarVqmHlHSqMeG6
            g8lhvmQm/xPGYuR25H4s7qAfULL5dzMrcqcZH/QgMcPxrZkMAHWCCG7b7BeHDug7
            JJzA+lmEFi6t4YWUcd1+Si5yacwVDoiWrq0esGrvEN1ajxeYvQj9vlr7/PquuNC9
            CAPgS/Ilmzig6QzlVtYcvVTyOw3+rxx2C41y1X0T6Qm/0ywKWBU1oO2yrJksXqPY
            444TxgnMDYSlkl7Hn9MRn3+hY8YUdK7CPKhEqyvQNS13joJjt1Mf3X9uFbkp8VHS
            UQFGn0icWrNJ4OVCba1dpvOt41Uwd2hYTmCofyNOcqvn5abYtH9rTB9i3A8QSiJK
            oyHSSlVXEVMMajvnGYJhoZjood/kK9qYFQDHWKFf6l31zA==
            =KGuj
            -----END PGP MESSAGE-----
          fp: 9C45D02EBB1DAE208E342A471A264B4B6D870D84
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
