apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux
spec:
  interval: 1h
  chart:
    spec:
      chart: metrics-server
      version: 3.11.0
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      interval: 1h
  releaseName: metrics-server
  targetNamespace: metrics-server
  storageNamespace: metrics-server
  values:
    args:
      - --kubelet-insecure-tls
    nodeSelector:
      node-role.kubernetes.io/control-plane: ""
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
