apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ${name}
  namespace: flux
spec:
  interval: 1h
  install:
    timeout: 50m
  releaseName: ${name}
  dependsOn:
    - name: nfs-subdir-external-provisioner
    - name: cert-manager
    - name: ingress-nginx
  chart:
    spec:
      chart: ${name}
      # version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: ${name}
      interval: 1h
  targetNamespace: ${namespace}
  storageNamespace: ${namespace}
  values:
    superuser:
      name: ${adminUser}
      email: ${adminEmail}
      password: ${adminPassword}
    image:
      tag: v3.7.3
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: ${issuer}
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: ${hostname}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: ${name}-tls
          hosts:
            - ${hostname}
    persistence:
      storageClass: null
    postgresql:
      enabled: true
      auth:
        postgresPassword: ${postgresPassword}
        password: ${dbPassword}
    redis:
      architecture: standalone
      auth:
        password: ${reddisPassword}
