apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: netbox
  namespace: flux
spec:
  interval: 10m
  path: "./apps/netbox"
  prune: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: kube
  postBuild:
    substituteFrom:
      - kind: Secret
        name: netbox
