apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: qemu-guest-agent
  namespace: flux
spec:
  interval: 1h
  releaseName: qemu-guest-agent
  targetNamespace: qemu-guest-agent
  storageNamespace: qemu-guest-agent
  chart:
    spec:
      chart: qemu-guest-agent
      version: 0.4.3
      sourceRef:
        kind: HelmRepository
        name: qemu-guest-agent
      interval: 1h
  values:
    nodeSelector:
      feature.node.kubernetes.io/cpu-cpuid.HYPERVISOR: "true"
    securityContext:
      seccompProfile:
        type: RuntimeDefault
