apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux
spec:
  interval: 10m
  path: "./base/cert-manager/cert-manager"
  prune: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: kube
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager-webhook
      namespace: cert-manager
