apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: issuers
  namespace: flux
spec:
  interval: 10m
  path: "./base/cert-manager/issuers"
  prune: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: kube
  dependsOn:
  - name: cert-manager
  postBuild:
    substituteFrom:
      - kind: Secret
        name: secrets
