apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - cilium
  - flux
  - ingress-nginx
  - metrics-server
  - nfs-subdir-external-provisioner
  - node-feature-discovery
  - qemu-guest-agent
