apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux.yaml
patches:
  - target:
      kind: Deployment
    patch: |-
      kind: not-important
      metadata:
        name: not-important
      spec:
        template:
          spec:
            nodeSelector:
              node-role.kubernetes.io/control-plane: ""
