apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ${name}
  namespace: flux
spec:
  interval: 1h
  install:
    timeout: 50m
  releaseName: ${name}
  dependsOn:
    - name: nfs-subdir-external-provisioner
    - name: cert-manager
    - name: ingress-nginx
  chart:
    spec:
      chart: ${name}
      version: 10.0.1
      sourceRef:
        kind: HelmRepository
        name: ${name}
      interval: 1h
  targetNamespace: ${namespace}
  storageNamespace: ${namespace}
  values:
    image:
      tag: 1.21.7
    ssh:
      type: NodePort
      port: 30022
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: ${issuer}
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: ${hostname}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: ${name}-tls
          hosts:
            - ${hostname}
    gitea:
      admin:
        username: ${adminUsername}
        password: ${adminPassword}
        adminEmail: ${adminEmail}
      config:
        server:
          LANDING_PAGE: explore
    postgresql-ha:
      enabled: false
    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            username: ${dbUsername}
            password: ${dbPassword}
